title: "HPC & Climate Analytics Portfolio"
author:
  name: "IGomezLeal"
description: "Astrophysics · Numerical Modeling · Data Science"

theme: minima

github_username: IGomezLeal

plugins:
  - jekyll-feed
  - jekyll-seo-tag
