# Settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  
# Minima-specific settings
minima:
  skin: classic
  
# Esto le dice a Jekyll que procese los archivos de forma estricta
markdown: kramdown
highlighter: rouge
