title: "HPC & Climate Analytics Portfolio"
author:
  name: "IGomezLeal"
description: "Astrophysics · Numerical Modeling · Data Science"

# Usamos una versión estable específica para evitar errores de 2026
remote_theme: "jekyll/minima@0b7ca6b"

# Configuración obligatoria para Minima v3
minima:
  skin: classic
  social_links:
    - { platform: github, user_username: IGomezLeal }

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
